apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.1-20190430
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  network:
    hostNetwork: false
  storage: # cluster level storage configuration and selection
    useAllNodes: false  # 目前还不知道如何配置亲和性索性就全部节点了，这会导致 有一个 master的prepare 因为我的master 没有挂载磁盘
    useAllDevices: true
    nodes:
      - name: "node1"
        devices:
          - name: "vdb"