apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-pv
  labels:
    pv : nginx-nfs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs-share/redis
    server: 172.16.50.146