apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-pv
  labels:
    pv : nginx-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs-share/nginx
    server: 172.26.9.41


